### ISSUE TITLE
Running for the first time after installation failed

### ISSUE THREAD

**Issue by EwetoyeIbrahim** [EwetoyeIbrahim/Flask-Marketplace#8]
Steps to reproduce:
1. Clone the repo
2. Install the requirement.txt file
3. Run the run.py file

Expected: The program should run without error

Result: It throws the error below on Linux
```
Traceback (most recent call last):
  File "run.py", line 9, in <module>
    app = create_app(os.getenv('CONFIG_NAME', default='default'))
  File "/usr/local/Flask-Marketplace/factory.py", line 24, in create_app
    import users_module.models
  File "/usr/local/Flask-Marketplace/users_module/__init__.py", line 3, in <module>
    from .models import db, User, Role, UserAdmin, RoleAdmin
  File "/usr/local/Flask-Marketplace/users_module/models.py", line 9, in <module>
    from flask_admin.contrib import sqla
  File "/usr/local/lib/python3.8/dist-packages/flask_admin/contrib/sqla/__init__.py", line 2, in <module>
    from .view import ModelView
  File "/usr/local/lib/python3.8/dist-packages/flask_admin/contrib/sqla/view.py", line 18, in <module>
    from flask_admin.contrib.sqla.tools import is_relationship
  File "/usr/local/lib/python3.8/dist-packages/flask_admin/contrib/sqla/tools.py", line 4, in <module>
    from sqlalchemy.ext.declarative.clsregistry import _class_resolver
ModuleNotFoundError: No module named 'sqlalchemy.ext.declarative.clsregistry'
```

**Comment by EwetoyeIbrahim** [comment]
Cause:
The error is a result of  the use of `clsregistry` by Flask-Admin. See [issue 6065](https://github.com/sqlalchemy/sqlalchemy/issues/6065)on sqlalchemy repo for more.

Solution:
Pending the time this gets resolved in Sqlalchemy, we escape it by downgrading Sqlalchemy to 1.3.*.
Thus, after installing the requirements simply follow by `pip install --upgrade SQLAlchemy==1.3.23`.

This will be added to the installation part of the ReadMe in the next commit.

**Comment by EwetoyeIbrahim** [comment]
Seems, the sweetest way to handle this would be to include `SQLAlchemy==1.3.23` in the requirements.txt file. As such, no additional step would be required.
